
const CATALOG_URL='data/catalog.json';
let catalog=[], cart=JSON.parse(localStorage.getItem('sonara-cart')||'[]'), wishlist=JSON.parse(localStorage.getItem('sonara-wishlist')||'[]');

const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(n);
function save(){localStorage.setItem('sonara-cart',JSON.stringify(cart));localStorage.setItem('sonara-wishlist',JSON.stringify(wishlist));updateCounts();}
function updateCounts(){document.querySelectorAll('[data-cart-count]').forEach(e=>e.textContent=cart.reduce((a,x)=>a+x.qty,0));document.querySelectorAll('[data-wish-count]').forEach(e=>e.textContent=wishlist.length);}
function toast(msg){let t=document.querySelector('.toast');if(!t){t=document.createElement('div');t.className='toast';document.body.appendChild(t)}t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}
function addToCart(slug){const p=catalog.find(x=>x.slug===slug);if(!p)return;const item=cart.find(x=>x.slug===slug);if(item)item.qty++;else cart.push({slug,qty:1});save();toast(`${p.name} added to cart`)}
function toggleWish(slug,btn){if(wishlist.includes(slug)){wishlist=wishlist.filter(x=>x!==slug);btn.textContent='♡'}else{wishlist.push(slug);btn.textContent='♥'}save();toast(wishlist.includes(slug)?'Added to wishlist':'Removed from wishlist')}
function productCard(p){return `<article class="product"><div class="product-media"><span class="badge">${p.badge}</span><button class="heart" onclick="toggleWish('${p.slug}',this)">${wishlist.includes(p.slug)?'♥':'♡'}</button><a href="products/${p.slug}.html"><img src="assets/images/products/${p.image}" alt="${p.name}"></a></div><div class="product-info"><small>${p.category}</small><h3>${p.name}</h3><div class="rating">★★★★★ <span class="muted">(${p.reviews})</span></div><div class="price">${money(p.price)}</div><p class="muted">${p.description}</p><div class="product-actions"><a class="btn" href="products/${p.slug}.html" style="text-align:center">Details</a><button class="add" onclick="addToCart('${p.slug}')">Add to cart</button></div></div></article>`}
function renderProducts(list,target='product-grid'){const el=document.getElementById(target);if(el)el.innerHTML=list.map(productCard).join('');}
function openCart(){document.querySelector('.drawer')?.classList.add('open');document.querySelector('.overlay')?.classList.add('open');renderCart()}
function closeCart(){document.querySelector('.drawer')?.classList.remove('open');document.querySelector('.overlay')?.classList.remove('open')}
function renderCart(){const box=document.querySelector('[data-cart]');if(!box)return;if(!cart.length){box.innerHTML='<p class="muted">Your cart is empty.</p>';return}box.innerHTML=cart.map(i=>{const p=catalog.find(x=>x.slug===i.slug);return `<div class="cart-item"><img src="assets/images/products/${p.image}" alt="${p.name}"><div><b>${p.name}</b><div>${i.qty} × ${money(p.price)}</div><button onclick="removeCart('${p.slug}')">Remove</button></div></div>`}).join('')+`<hr><h3>Total: ${money(cart.reduce((s,i)=>s+(catalog.find(p=>p.slug===i.slug).price*i.qty),0))}</h3><button class="btn primary" onclick="toast('Checkout demo ready')">Proceed to checkout</button>`}
function removeCart(slug){cart=cart.filter(x=>x.slug!==slug);save();renderCart()}
async function init(){try{catalog=await fetch(CATALOG_URL).then(r=>r.json());}catch(e){console.error(e);return}renderProducts(catalog.slice(0,8));updateCounts();const q=document.getElementById('search');if(q)q.addEventListener('input',()=>renderProducts(catalog.filter(p=>(p.name+' '+p.category+' '+p.description).toLowerCase().includes(q.value.toLowerCase()))));document.querySelectorAll('[data-category]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-category]').forEach(x=>x.classList.remove('active'));b.classList.add('active');const c=b.dataset.category;renderProducts(c==='All'?catalog:catalog.filter(p=>p.category===c))}));}
document.addEventListener('DOMContentLoaded',init);
